### ISSUE TITLE
About CMakeLists.txt

### ISSUE THREAD

**Issue by Tian-one** [KugaMaxx/cuke-emlb#1]
Hi, I am very interested in your work, but when I tried to run setup.sh, I encountered an issue with the missing CMakeLists.txt file.

**Comment by KugaMaxx** [comment]
Hi, could you please point out the missing one, I'll try to upload it later

**Comment by Tian-one** [comment]
Thanks for your response! It may missing main directory CmakeLists, i.e. /cuke-emlb/CmakeLists.txt

**Comment by Tian-one** [comment]
By the way, are the codes about EvZoom and EDnCNN still not available now?

**Comment by KugaMaxx** [comment]
Have you checked `src/_denoisor/`? I have uploaded EDnCNN as `event_denoise_convolution_network`. I'm still trying to convert EvZoom to a C++ version, so it is not mature enough to be publicly available.
