### ISSUE TITLE
Datasets File type

### ISSUE THREAD

**Issue by MohamadHalwani** [KugaMaxx/cuke-emlb#11]
Hi,

Thank you for your efforts. 

So this package only supports .aedat4 data files ? I wonder if I have rosbag file that has the event stream topic, are there any method to convert it to aedat4 ?! 

I spend more than 3 hours on this with no luck.

**Comment by KugaMaxx** [comment]
Hi, @MohamadHalwani ! The answer is YES, if you have successfully installed this project, the `dv_toolkit` will have already existed in your environment so that you can directly use and please refer to this [tutorial](https://github.com/KugaMaxx/yam-toolkit), which supports both C++ and python. 

For example:

```python
import dv_toolkit as kit

# Initialize MonoCameraData
data = kit.MonoCameraData()

# Emplace back event elements, the function arguments are:
# timestamp, x, y, polarity
store = kit.EventStorage()
store.emplace_back(dv.now(), 0, 0, False)
store.emplace_back(dv.now(), 1, 1, True)
store.emplace_back(dv.now(), 2, 2, False)
store.emplace_back(dv.now(), 3, 3, True)

# Assignment value to MonoCameraData
data["events"] = store;

# Initialize MonoCameraData
data = kit.MonoCameraData()

# Initialize resolution
resolution = (346, 260)

# Initialize MonoCameraWriter
writer = kit.io.MonoCameraWriter("/path/to/file.aedat4", resolution)

# Write MonoCameraData
writer.writeData(data)

```

Let me know if you have any questions!

**Comment by MohamadHalwani** [comment]
Thanks its working now !

**Comment by wzz-z** [comment]
When I tried to use the above method to create a test aedat4 dataset and input it, the following error occurred, as shown in the figures. Figure 1 displays the results of running the code that generates the aedat4 data and using the generated data as model input.

![Image](https://github.com/user-attachments/assets/083d8c61-b0f0-4b8a-8ee8-080de0e47bb7)

 the code:
``import os
import dv
import numpy as np
import dv_toolkit as kit
import pandas as pd

input_file = '/home/ssoelab/snap/code/cuke-emlb/data/demo/txt/Car_03_2.5.txt'  
output_file = '/home/ssoelab/snap/code/cuke-emlb/data/demo/samples/output.aedat4'  

Txt_data = pd.read_csv(input_file,skiprows=0,delimiter=' ',dtype={'column1':np.int64,'column2':np.int16,'column3':np.int16,'column4':np.int8})
Txt_data = Txt_data.values
data = kit.MonoCameraData()
store = kit.EventStorage()
for i in range(Txt_data.shape[0]):
    store.emplace_back(int(Txt_data[i,0]),int(Txt_data[i,1]),int(Txt_data[i,2]),bool(Txt_data[i,3]))
print(store)
data["events"]  = store
data = kit.MonoCameraData()
writer = kit.io.MonoCameraWriter( '/home/ssoelab/snap/code/cuke-emlb/data/demo/samples/output_cs.aedat4',(346,260))
writer.writeData(data)``
