### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by CheungBH** [KugaMaxx/cuke-emlb#4]
Hello. Thanks for your great work.

I wonder whether you have the plan to release the training code?

**Comment by KugaMaxx** [comment]
Hi, @CheungBH ! Thank you for your attention to my work. As the code is based on the implementation of [Libtorch](https://pytorch.org/cppdocs/installing.html), it is difficult to replicate the training process in C++, so there is no relevant plan in the short term. :disappointed:

**Comment by CheungBH** [comment]
Thank you for your reply. 
I want to evaluate your edncnn & mplf model, but a problem occurs that:
ImportError: cannot import name 'event_denoise_convolution_network' from 'modules.python' (unknown location)
Are there any suggestions for solving it? I noticed that the hpp files in **include/denoisors** are complete, but there are only 6 .so files in **module/python** folder.

![Screenshot 2024-01-26 at 4 55 07 PM](https://github.com/KugaMaxx/cuke-emlb/assets/39186017/34f7e2a9-ea99-4141-a81e-10d51a181d2c)

**Comment by KugaMaxx** [comment]
I think you need try:
```bash
# create folder
mkdir build && cd build

# compile with samples
CC=gcc-10 CXX=g++-10 cmake .. -DEMLB_ENABLE_PYTHON=ON -DTORCH_DIR=<path/to/libtorch>/share/cmake/Torch/

# generate library
cmake --build . --config Release
```
And you will see `.cpython-38-x86_64-linux-gnu.so` file in `/modules/python`.
![screenshot](https://github.com/KugaMaxx/cuke-emlb/assets/118443479/3967b392-b9f2-46a1-b117-3595f171e718)

Check if `event_denoise_convolution_network.cpython-38-x86_64-linux-gnu.so` and `multi_layer_perceptron_filter.cpython-38-x86_64-linux-gnu.so` exist, then run the code.
